name: DreamAPI
version: '${version}'
main: com.github.dreamdevelopments.dreamapi.DreamAPIPlugin
api-version: '1.13'
softdepend: [ProtocolLib, Geyser-Spigot]
commands:
  verify:
    description: Verify your purchase